/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bankacilik;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.ImageIcon;

public class KrediBasvurusu extends javax.swing.JFrame {

    /**
     * Creates new form KrediBasvurusu
     */
    String tc;

    public KrediBasvurusu(String tc) {
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("/images/bank.png")).getImage());
        setLocationRelativeTo(null);
        setVisible(true);
        setResizable(false);
        this.tc = tc;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(23, 23, 26));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Kredi başvuru nedeniniz nedir?");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(42, 46, 210, 16);

        jButton1.setBackground(new java.awt.Color(12, 63, 122));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Başvur");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(140, 250, 100, 30);

        jTextArea1.setBackground(new java.awt.Color(12, 63, 122));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(40, 70, 330, 83);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("İstediğiniz kredi miktarı nedir?");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 170, 170, 16);

        jTextField1.setBackground(new java.awt.Color(12, 63, 122));
        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jTextField1);
        jTextField1.setBounds(40, 190, 160, 24);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Kredi süresini seçiniz.");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(220, 170, 130, 16);

        jComboBox1.setBackground(new java.awt.Color(12, 63, 122));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 yıl", "3 yıl", "5 yıl", "7 yıl", "10 yıl", " " }));
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(220, 190, 110, 26);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String tarih = "";

        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("M");
        DateTimeFormatter dtf2 = DateTimeFormatter.ofPattern("u");
        DateTimeFormatter dtf3 = DateTimeFormatter.ofPattern("d");
        if (jComboBox1.getSelectedIndex() == 0) {
            LocalDateTime ay = LocalDateTime.now();
            LocalDateTime yil = LocalDateTime.now().plusYears(1);
            tarih = dtf3.format(ay) + "." + dtf.format(ay) + "." + dtf2.format(yil);
        } else if (jComboBox1.getSelectedIndex() == 1) {
            LocalDateTime ay = LocalDateTime.now();
            LocalDateTime yil = LocalDateTime.now().plusYears(3);
            tarih = dtf3.format(ay) + "." + dtf.format(ay) + "." + dtf2.format(yil);
        } else if (jComboBox1.getSelectedIndex() == 2) {
            LocalDateTime ay = LocalDateTime.now();
            LocalDateTime yil = LocalDateTime.now().plusYears(5);
            tarih = dtf3.format(ay) + "." + dtf.format(ay) + "." + dtf2.format(yil);
        } else if (jComboBox1.getSelectedIndex() == 3) {
            LocalDateTime ay = LocalDateTime.now();
            LocalDateTime yil = LocalDateTime.now().plusYears(7);
            tarih = dtf3.format(ay) + "." + dtf.format(ay) + "." + dtf2.format(yil);
        } else if (jComboBox1.getSelectedIndex() == 4) {
            LocalDateTime ay = LocalDateTime.now();
            LocalDateTime yil = LocalDateTime.now().plusYears(10);
            tarih = dtf3.format(ay) + "." + dtf.format(ay) + "." + dtf2.format(yil);
        }

        Musteri.krediBasvur(tc, jTextArea1.getText(), jTextField1.getText(), tarih);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KrediBasvurusu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KrediBasvurusu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KrediBasvurusu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KrediBasvurusu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
