/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bankacilik;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author MSI
 */
public class PersonelKaydet extends javax.swing.JFrame {

    /**
     * Creates new form MusteriKaydol
     */
    Yonetici y1;
    JButton b1;
    public PersonelKaydet(Yonetici y1,JButton b1) {
        this.y1=y1;
        this.b1=b1;
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("/images/bank.png")).getImage());
        setLocationRelativeTo(null);
        setVisible(true);
        setResizable(false);
        setTitle("Personel Kaydet");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        adBox = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        soyadBox = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        sifreBox = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        annekizlikBox = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        telBox = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        emailBox = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        maasBox = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        dgBox = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        tcBox = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        maasGunBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(470, 470));
        setMinimumSize(new java.awt.Dimension(470, 470));
        setPreferredSize(new java.awt.Dimension(470, 470));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(23, 23, 26));
        jPanel1.setMaximumSize(new java.awt.Dimension(470, 470));
        jPanel1.setPreferredSize(new java.awt.Dimension(470, 470));
        jPanel1.setLayout(null);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ad");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(50, 30, 30, 16);

        adBox.setBackground(new java.awt.Color(102, 102, 102));
        adBox.setForeground(new java.awt.Color(255, 255, 255));
        adBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adBoxActionPerformed(evt);
            }
        });
        jPanel1.add(adBox);
        adBox.setBounds(50, 50, 150, 22);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Soyad");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(50, 100, 50, 16);

        soyadBox.setBackground(new java.awt.Color(102, 102, 102));
        soyadBox.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(soyadBox);
        soyadBox.setBounds(50, 120, 150, 22);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Şifre");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(260, 100, 40, 16);

        sifreBox.setBackground(new java.awt.Color(102, 102, 102));
        sifreBox.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(sifreBox);
        sifreBox.setBounds(260, 120, 150, 22);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Anne Kızlık Soyadı");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(50, 240, 130, 16);

        annekizlikBox.setBackground(new java.awt.Color(102, 102, 102));
        annekizlikBox.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(annekizlikBox);
        annekizlikBox.setBounds(50, 260, 150, 22);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Telefon");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(50, 160, 80, 16);

        telBox.setBackground(new java.awt.Color(102, 102, 102));
        telBox.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(telBox);
        telBox.setBounds(50, 180, 150, 22);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("E-mail");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(260, 160, 90, 16);

        emailBox.setBackground(new java.awt.Color(102, 102, 102));
        emailBox.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(emailBox);
        emailBox.setBounds(260, 180, 150, 22);

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("<html>Doğum tarihi<br>(Aralarda nokta olacak şekilde)<html>");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(260, 220, 170, 32);

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Maaş");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(50, 310, 130, 16);

        maasBox.setBackground(new java.awt.Color(102, 102, 102));
        maasBox.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(maasBox);
        maasBox.setBounds(50, 330, 150, 22);

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Maaş günü");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(260, 310, 170, 16);

        dgBox.setBackground(new java.awt.Color(102, 102, 102));
        dgBox.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(dgBox);
        dgBox.setBounds(260, 260, 150, 22);

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setText("Personeli kaydet");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(170, 370, 120, 40);

        tcBox.setBackground(new java.awt.Color(102, 102, 102));
        tcBox.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(tcBox);
        tcBox.setBounds(260, 50, 150, 22);

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("T.C. Kimlik No");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(260, 30, 90, 16);

        maasGunBox.setBackground(new java.awt.Color(102, 102, 102));
        maasGunBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28" }));
        jPanel1.add(maasGunBox);
        maasGunBox.setBounds(260, 330, 140, 22);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 470, 470);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adBoxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            boolean sit = false;
            // TODO add your handling code here:
            File file = new File("src/files/personelInfo.txt");
            BufferedReader br = new BufferedReader(new FileReader(file));
            String st;
            while ((st = br.readLine()) != null) {
                if (st.split("/")[0].equals(tcBox.getText())) {
                    sit = true;
                }
            }
            if ((tcBox.getText().equals("") || sifreBox.getText().equals("") || annekizlikBox.getText().equals("") || adBox.getText().equals("") || soyadBox.getText().equals("") || telBox.getText().equals("") || emailBox.getText().equals("") || dgBox.getText().equals("") || maasBox.getText().equals(""))) {
                JOptionPane.showMessageDialog(null, "Boş alan bırakamazsınız!", "Hata", JOptionPane.WARNING_MESSAGE);
            } else if (sit == true) {
                JOptionPane.showMessageDialog(null, "Zaten bu bankada bu personel kayıtlı!", "Hata", JOptionPane.WARNING_MESSAGE);
            }
            else y1.personelEkle(b1,tcBox.getText()+"/"+sifreBox.getText()+"/"+annekizlikBox.getText()+"/"+adBox.getText()+"/"+soyadBox.getText()+"/"+telBox.getText()+"/"+emailBox.getText()+"/"+dgBox.getText()+"/"+maasGunBox.getSelectedItem().toString()+"/"+maasBox.getText());

        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PersonelKaydet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PersonelKaydet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PersonelKaydet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PersonelKaydet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */


    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adBox;
    private javax.swing.JTextField annekizlikBox;
    private javax.swing.JTextField dgBox;
    private javax.swing.JTextField emailBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField maasBox;
    private javax.swing.JComboBox<String> maasGunBox;
    private javax.swing.JTextField sifreBox;
    private javax.swing.JTextField soyadBox;
    private javax.swing.JTextField tcBox;
    private javax.swing.JTextField telBox;
    // End of variables declaration//GEN-END:variables
}
